app:
  cookie:
    secure: true  # 기본값: HTTPS (운영 환경 기준). local 프로필에서 false로 override

spring:
  profiles:
    active: local # 기본 실행 프로필
  config:
    import:
      - optional:classpath:logging.yml # 공통 로깅 설정 불러오기
      - optional:classpath:config/application-${spring.profiles.active}.yml # Submodule 설정
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update # 스키마를 변경하지 않음
    properties:
      hibernate:
        default_batch_fetch_size: 100 # N+1 최적화
  batch:
    jdbc:
      initialize-schema: always  # 또는 embedded, never
    job:
      enabled: false  # 애플리케이션 시작 시 자동 실행 방지

# Swagger UI 설정
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
  packages-to-scan:
    - com.swcampus.api
  paths-to-match:
    - /api/**
