spring:
  application:
    name: sw-campus-server

  profiles:
    default: local
    group:
      local: local
      staging: staging
      prod: prod
      ddl-gen: ddl-gen

  config:
    import:
      - optional:classpath:logging.yml # 공통 로깅 설정 불러오기
      - optional:classpath:config/application-${spring.profiles.active}.yml

  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 100 # N+1 최적화

  # Spring Batch
  batch:
    jdbc:
      initialize-schema: never  # 또는 embedded, never
    job:
      enabled: false  # 애플리케이션 시작 시 자동 실행 방지

  # Mail (SMTP)
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# Swagger UI 설정
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
  packages-to-scan:
    - com.swcampus.api
  paths-to-match:
    - /api/**
